### ISSUE TITLE
mixpanel-java:1.1.2 is available

### ISSUE THREAD

**Issue by joeatwork** [alxndrsn/grails-mixpanel-plugin#3]
Changes are internal bug fixes only - there aren't any changes to the library interface. You may want to consider using the new version in your BuildConfig.

Thanks!

**Comment by alxndrsn** [comment]
Thanks, will do.

**Comment by alxndrsn** [comment]
Actually this isn't available in Maven Central yet, so it doesn't work.  Is there a mixpanel maven repo I can reference?

**Comment by joeatwork** [comment]
Oh! That's our problem- I'll make sure it's available right away!

https://github.com/mixpanel/mixpanel-java/issues/4

**Comment by joeatwork** [comment]
Sorry about the hassle! I've just released (and confirmed the availability) of mixpanel-java-1.1.3 on Maven central.

Thanks again!

**Comment by alxndrsn** [comment]
Done, and thanks again.

**Comment by joeatwork** [comment]
Thank you so much!
