### ISSUE TITLE
Triggering events breaks when map/list is passed in data variable

### ISSUE THREAD

**Issue by vaneyck** [alxndrsn/grails-mixpanel-plugin#4]
The plugins handles passing a single object very well

```
event for:'security', topic:'userLogged', data:session.user
```

But when a map is passed in the data variable, the plugin breaks. The plugin could be more robust and handle lists and maps e.g

```
event for:'security', topic:'userLogged', data:[user:session.user]
event for:'security', topic:'userLogged', data:[object1, object2]
```

**Comment by alxndrsn** [comment]
Presumably caused by passing non-JSONable objects at https://github.com/alxndrsn/grails-mixpanel-plugin/blob/master/grails-app/services/mixpanel/MixpanelService.groovy#L27

Do you have a stacktrace for the error you get?

**Comment by alxndrsn** [comment]
Fixed, AFAIK
