### ISSUE TITLE
User id not available for events

### ISSUE THREAD

**Issue by hbomze** [alxndrsn/grails-mixpanel-plugin#5]
When using the event form of the call rather then directly calling logEvent, the SpringSecurityService does not have access to the user.  I suspect this is because the thread processing the event is not the request thread.  An alternative for providing the unique user id to MixPanel must be provided.  A suggestion is to place it in the data portion of the event method call and implement a method in the MixpanelHelperService to extract it from the eventObject parameter.  The MixpanelHelperService can optionally remove that parameter from the eventObject if desired.

I would also suggest changing the createJson method to handle a Map as the eventObject.  The JSONObject constructor can take a Map.

The event call with a Map for the eventObject looks like:

event([for:'mynamespace', topic:'mytopic', data:['userId':"${userInstance.userNumber}", property1:'propertyValue']])

I would be happy to provide a version of the code that does all of this.

**Comment by alxndrsn** [comment]
Hey, interesting bug!  Will definitely check this out at my end.

Your fix sounds workable, but my original aims were:
- to avoid having to change the `event()` calls which might already be in an application - that way any event can be hooked for mixpanel tracking
- to avoid any direct dependence on Spring Security

Maybe this isn't feasible though - any thoughts?  Does the problem only occur when using asynchronous event processing?

Also feel free to submit a pull request if you've already got the code written and we can discuss it directly.

---

Ref passing a map to `createJson()`, is that [issue number 4](https://github.com/alxndrsn/grails-mixpanel-plugin/issues/4)?

Thanks for the feedback,

Alex

**Comment by alxndrsn** [comment]
This is fixed by https://github.com/alxndrsn/grails-mixpanel-plugin/pull/9
